# Serverless definition file
# --------------------------
# Defines Lambda functions to be deployed to AWS using the Serverless Framework.
# http://serverless.com
#
# This creates an API which proxies to lambda

service: node-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  memorySize: 128
  timeout: 15
  environment: ${file(env.yml):${opt:stage, self:provider.stage}}

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
